### PR TITLE
Feature/csv output

### LINKED ISSUE #12: CLI command to export CSV or JSON
When we opened this issue, the assumption was that either CSV or JSON would be the immediate output of the scraping utility. But now, our strategy is to have the parser load the data into a SQLite database, and then use a separate command to retrieve the data from the database and then export in either CSV or JSON.

### PR DESCRIPTION
**Pull request by jtcasper**
Closes #12 

I dropped click + args and simplified to stdin/stdout CSV output for my own development purposes, but I can drop that commit from this PR for now if you want.

### CODE REVIEW

**Comment by mscarey** [comment]
I'd like to keep the JSON output option, but CSV could be made the default. It looks like you wrote some code in `parse_hearings.parse_all` that will convert the dict format to be output as CSV, but it's not obvious to me how to extract that into its own function that only runs when the CSV flag is used. I think to use stdin or stdout instead of a file in a Click CLI, you replace the name of the infile or outfile with "-"

**Comment by jtcasper** [comment]
I haven't seen the value to Aaron and Shoshana of JSON output, which is partly why I stripped it out. Good to know about the Click CLI stdio operation, I moved away from those arguments because they didn't help when scaling this up to a 55K dataset that Aaron gave me.

I had to make the modifications in afae1d0 because of the fact that Firefox Web Content + Python building an array of dicts in memory was OOMing my computer, and neither could be reaped effectively, causing it to thrash and become unrecoverable. With that 55K dataset, I needed it to be able to resume where it left off, which stdio redirection helped greatly with.

Still, Firefox would OOM because it won't clear the Web Content sub-process it has running, so I ended up utilizing shell globbing to have the scraper work chunks that it could complete in ~20 minutes each, and allow the OS to reclaim the physical memory as necessary. At that point, building up a dict of arrays in memory just to JSON dump them was so far out of the question that I didn't really worry about it. I just needed to get this to scale for the requests they're handing me.

**Comment by mscarey** [comment]
So if I understand right, the size of the batch of case numbers the utility should handle depends on a balance of time and memory: if the batches are too small, it takes too much time to start up the Selenium process for each batch, but if the batches are too large, Selenium/Firefox eats up too much memory from loading too many pages at a time. But to break the case list into batches at all, there needs to be a function to stream the output to a file after loading each case. And that function only exists for CSV, not for JSON.

I think it would be helpful to have documentation about how a user can work with case lists that are too big for the results to fit into memory. I do want the Open Austin fork of the project to stay in a state where anyone can use it by following the readme without writing more code themselves.

**Comment by jtcasper** [comment]
I think it could exist for JSON, but you wouldn't be able to stream JSON-per-case and get a JSON array out of it, you'd have to implement your own wrapping to add brackets and comma terminate every line. I'm gonna close these two since they're ultimately too dependent on data structures, and SK has expressed wanting a different output for hearing-type details anyway, since the outputting multiple rows per case has too much noise.

**Pull request closed without merging**
