### PR TITLE
Feature/missing hearings

### PR DESCRIPTION
**Pull request by jtcasper**
Some persnickety errors prevent completing long runs when a CaseDetail page with no hearings recorded was encountered.

### CODE REVIEW

**Comment by jtcasper** [comment]
Tacked an empty zip code fix on

**Comment by jtcasper** [comment]
Un-tacked that, gonna include it in some unrelated zip-code fixes.

**Comment by mscarey** [comment]
Maybe pinning the dependencies could be a different PR. Do you have an example of a CaseDetail page with no hearings where these bugs occur, for testing?

**Comment by jtcasper** [comment]
I'm looking at J2-CV-20-001919 right now and it doesn't _currently_ have one. It wasn't what I was using to test when writing the code yesterday though.

**Comment by jtcasper** [comment]
Just realized there was a requirements-dev... whoops

**Pull request merged**
